#!/bin/bash
realpath='/home/pi/wfcamera'

montage ${realpath}/temp/image*.jpg -tile 2x2 -geometry +10+10 ${realpath}/temp/temp_montage_four.jpg
convert ${realpath}/temp/temp_montage_four.jpg -resize 256x256 ${realpath}/temp/temp_montage_thumbnail.jpg
montage ${realpath}/temp/temp_montage_four.jpg ${realpath}/assets/tcp_vertical.png -tile 2x1 -geometry +5+5 ${realpath}/temp/temp_montage_framed.jpg

montage ${realpath}/temp/image*.jpg -tile 1x4 -geometry +5+5 ${realpath}/temp/temp_montage_vert.jpg
montage ${realpath}/temp/temp_montage_vert.jpg ${realpath}/assets/tcp_horizontal.png -tile 1x2 -geometry +2+2 ${realpath}/temp/temp_montage_printframed.jpg
montage ${realpath}/temp/temp_montage_printframed.jpg -duplicate 1 -geometry +0+0 ${realpath}/temp/temp_montage_print.jpg

#rm ${realpath}/temp/temp_montage.jpg
#convert ${realpath}/temp/temp_montage_framed.jpg -resize 1000x1000 ${realpath}/temp/montage_preview.jpg
#suffix=$(date +%H%M%S)
#cp ${realpath}/temp/temp_montage1.jpg ${realpath}/montages/IMG_${suffix}.jpg
