#!/bin/bash
realpath='/home/pi/wfcamera'

#groups photos in a strip
montage ${realpath}/temp/image*.jpg -tile 1x4 -geometry +0+5 ${realpath}/temp/temp_mv.jpg
#adds watermark
montage ${realpath}/temp/temp_mv.jpg ${realpath}/assets/tcp_horizontal.png -tile 1x2 -geometry +0+0 ${realpath}/temp/temp_mv2.jpg
#doubles image
montage ${realpath}/temp/temp_mv2.jpg -background white -duplicate 1 -gravity east -geometry +20+0 ${realpath}/temp/temp_mvp.jpg

#rm ${realpath}/temp/temp_montage.jpg
#convert ${realpath}/temp/temp_montage_framed.jpg -resize 1000x1000 ${realpath}/temp/montage_preview.jpg
#suffix=$(date +%H%M%S)
#cp ${realpath}/temp/temp_montage1.jpg ${realpath}/montages/IMG_${suffix}.jpg
